/*
 * File: app/store/FieldStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.store.FieldStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'FieldStore',
            fields: [
                {
                    convert: function(v, rec) {
                        var value;
                        if(rec.get('cols_type') == 'colorchk'){
                            value = [];
                            var val;
                            for(var i=0; i<v.length; i++){
                                val = v[i].split('||');
                                value.push([val[1], val[0], v[i]]);
                            }
                        }
                        else{
                            value = v;
                        }
                        return value;
                    },
                    name: 'cols_data'
                },
                {
                    name: 'cols_idx'
                },
                {
                    name: 'cols_name'
                },
                {
                    name: 'cols_type'
                },
                {
                    convert: function(v, rec) {
                        var val = (v == 1)? true : false;
                        return val;
                    },
                    name: 'cols_share'
                },
                {
                    name: 'cols_option'
                },
                {
                    convert: function(v, rec) {
                        var val = (rec.get('cols_option') !== '')? getOption(rec.get('cols_option')) : {};
                        return val;
                    },
                    name: 'option'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});