/*
 * File: app/view/ActorWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.ActorWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.actorwindow',

    requires: [
        'Actor.view.ActorWindowViewModel',
        'Actor.view.ActorWindowViewController',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    config: {
        categoryId: '',
        openner: null,
        isSimple: true
    },

    controller: 'actorwindow',
    viewModel: {
        type: 'actorwindow'
    },
    alwaysOnTop: true,
    modal: true,
    cls: 'upload-form',
    height: 750,
    width: 1000,
    bodyStyle: {
        'background-color': '#ffffff'
    },
    ghost: false,
    maximizable: true,
    defaultListenerScope: true,

    layout: {
        type: 'border',
        padding: 20
    },
    items: [
        {
            xtype: 'treepanel',
            region: 'west',
            split: true,
            itemId: 'tree',
            width: 230,
            bodyBorder: false,
            hideHeaders: true,
            rootVisible: false,
            bind: {
                title: '{category}'
            },
            listeners: {
                itemclick: {
                    fn: 'onTreeItemClick',
                    scope: 'controller'
                }
            }
        },
        {
            xtype: 'container',
            region: 'center',
            split: true,
            itemId: 'listContainer',
            style: 'border:1px solid #cecece',
            layout: 'fit',
            items: [
                {
                    xtype: 'gridpanel',
                    numOfItem: '30',
                    itemId: 'list',
                    header: false,
                    title: 'Data list',
                    columns: [
                        {
                            xtype: 'gridcolumn'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            itemId: 'pagingToolbar',
                            displayInfo: true,
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'fdSearch',
                                    margin: '0 0 0 3',
                                    width: 100,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnFindIt',
                                    margin: '0 6 0 6',
                                    glyph: 'xf002@FontAwesome',
                                    listeners: {
                                        click: 'onBtnFindItClick'
                                    }
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: 'onPagingToolbarAfterRender',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforerender: {
            fn: 'onWindowBeforeRender',
            scope: 'controller'
        }
    },

    onBtnFindItClick: function(button, e, eOpts) {
        var val = button.up('pagingtoolbar').down('#fdSearch').getValue();
        var ctrl = getController('Main');
        var query = "se_all=" + val;
        if(button.up('window').categoryId !== undefined) query += '&ca_id=' + button.up('window').categoryId;
        getController('Main').getServerData(button.up('window').categoryId, query, button.up('window').getGrid());
    },

    getGrid: function() {
        var grid = this.down('#list');
        if(this.down('#galleryView') !== null) grid = this.down('#galleryView');
        return grid;
    },

    disableEvent: function() {
        this.down('#tree').getSelectionModel().un('select', this.down('#tree').onSelect);
    },

    setColorChipGrid: function() {
        this.down('#list').destroy();
        var tpl = '<table style="width:100%;cursor:pointer">';
        tpl    += '	<tr>';
        tpl    += '		<td style="width:115px;height:65px;padding-left:10px">';
        tpl    += '			<span style="font-weight:bold;">CODE</span> : {bd_subject}<br><span style="font-weight:bold">HEX</span> : {idcolorHex}';
        tpl    += '		</td>';
        tpl    += '		<td style="background-color:{idcolorHex}">';
        tpl    += '		</td>';
        tpl    += '	</tr>';
        tpl    += '</div>';
        var chipGrid = Ext.create(
            {
                xtype:'panel',
                type:'colorChip',
                itemId:'list',
                scrollable:true,
                items:[
                    {
                        xtype:'dataview',
                        itemId:'galleryView',
                        type:'colorChip',
                        itemTpl:tpl,
                        itemSelector:'table',
                    }
                ],
                dockedItems: [
                    {
                        xtype: 'pagingtoolbar',
                        dock: 'bottom',
                        itemId: 'pagingToolbar',
                        displayInfo: true,
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'fdSearch',
                                margin: '0 0 0 3',
                                width: 100,
                                fieldLabel: 'Label',
                                hideLabel: true
                            },
                            {
                                xtype: 'button',
                                itemId: 'btnFindIt',
                                margin: '0 6 0 6',
                                glyph: 'xf002@FontAwesome',
                                listeners: {
                                    click: 'onBtnFindItClick'
                                }
                            }
                        ],
                        listeners: {
                            afterrender: {
                                fn: 'onPagingToolbarAfterRender',
                                scope: 'controller'
                            }
                        }
                    }
                ]
            });
        this.down('#listContainer').add(chipGrid);
    }

});