/*
 * File: app/view/ColorPickerWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.ColorPickerWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.colorpickerwindow',

    requires: [
        'Actor.view.ColorPickerWindowViewModel',
        'Actor.view.ColorPickerWindowViewController'
    ],

    config: {
        record: null,
        idx: -1
    },

    controller: 'colorpickerwindow',
    viewModel: {
        type: 'colorpickerwindow'
    },
    height: 250,
    itemId: 'colorPickerWin',
    width: 400,
    title: 'My Window',

    listeners: {
        beforerender: 'onWindowBeforeRender'
    }

});