/*
 * File: app/view/DeletableUnit.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.DeletableUnit', {
    extend: 'Ext.container.Container',
    alias: 'widget.deletableunit',

    requires: [
        'Actor.view.DeletableUnitViewModel',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'deletableunit'
    },
    style: {
        'border-radius': '5px',
        border: '1px solid #cecece'
    },

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            itemId: 'content',
            padding: 5
        },
        {
            xtype: 'button',
            handler: function(button, e) {
                button.up('container').destroy();
            },
            itemId: 'btnDestory',
            style: 'border-radius:0',
            width: 23,
            text: '-'
        }
    ],

    addContent: function(component) {
        var ca = this.down('#content');
        ca.add(component);
    },

    addImage: function(src) {
        var iStyle = 'background-image:url('+src+');background-size:cover;background-position:center';
        var image = {
            xtype:'component',
            style:iStyle
        };
        this.insert(0, image);
    }

});