/*
 * File: app/view/GridColorChip.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.GridColorChip', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.gridcolorchip',

    requires: [
        'Actor.view.GridColorChipViewModel',
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    config: {
        type: 'colorChip'
    },

    viewModel: {
        type: 'gridcolorchip'
    },
    scrollable: true,
    bodyPadding: 25,
    bodyStyle: 'border-top:1px solid #cecece !important',
    closable: true,

    items: [
        {
            xtype: 'dataview',
            itemId: 'galleryView',
            tpl: Ext.create('Ext.XTemplate', 
                '<tpl for=".">',
                '    <div style="display:inline-block;width:100px;height:140px" title="{delta}">',
                '            <div class="gunit" style="width:100px;height:100px;background-color:{[this.getCode(values)]}">',
                '            </div>',
                '            <div style="width:100%;font-size:12px">',
                '                <table cellpadding="0" cellspacing="0">',
                '                    <tr>',
                '                        <td style="text-align:left;width:36px;color:#7ba3b0;font-weight:600">CODE</td>',
                '                        <td style="font-weight:700">{bd_subject}</td>',
                '                    </tr>',
                '                    <tr>',
                '                        <td style="text-align:left;color:#7ba3b0;font-weight:600">HEX</td>',
                '                        <td>{[this.getCode(values)]}</td>',
                '                    </tr>                    ',
                '                </table>',
                '',
                '        </div>        ',
                '    </div>',
                '</tpl>',
                {
                    getCode: function(values) {
                        var val = values.idcolorHex;
                        if(val.indexOf('#') == -1) val = '#' + val;
                        return val.trim();
                    }
                }
            ),
            itemSelector: 'div.gunit',
            selectedItemCls: 'colorchip-selected'
        }
    ]

});