/*
 * File: app/view/GridText.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.GridText', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.gridtext',

    requires: [
        'Actor.view.GridNormalViewModel1',
        'Actor.view.GridNormalViewController1',
        'Ext.grid.column.Column',
        'Ext.selection.CheckboxModel'
    ],

    config: {
        type: 'text'
    },

    controller: 'gridtext',
    viewModel: {
        type: 'gridtext'
    },
    componentCls: 'gridtext',
    height: 250,
    width: 400,
    closable: true,
    title: 'My Grid Panel',

    columns: [
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'string',
            text: 'String'
        }
    ],
    selModel: {
        selType: 'checkboxmodel'
    },
    listeners: {
        headerclick: 'onGridNormalHeaderClick'
    }

});