/*
 * File: app/view/GridGallery.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.GridGallery', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.gridgallery',

    requires: [
        'Actor.view.GridGalleryViewModel',
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    config: {
        type: 'gallery'
    },

    viewModel: {
        type: 'gridgallery'
    },
    scrollable: true,
    bodyPadding: 25,
    bodyStyle: 'border-top:1px solid #cecece !important',
    closable: true,

    items: [
        {
            xtype: 'dataview',
            itemId: 'galleryView',
            tpl: Ext.create('Ext.XTemplate', 
                '<tpl for=".">',
                '    <div class="gallery-unit gunit">',
                '        <div class="gallery-unit-wrap">',
                '            <div class="gallery-unit-image" style="background-image:url({[this.checkIfImage(values)]})">',
                '            </div>',
                '            <div style="width:100%;font-size:12px;padding:5px">',
                '                <tpl if="values.bd_file.length &gt; 1">',
                '                    <div id="viewAttached_{bd_idx}" style="cursor:pointer;display:inline-box;float:left;height:16px;padding:0 2px 0 2px;margin-top:1px;background-color:black;color:white">{bd_file.length}</div>',
                '                </tpl>',
                '                <div style="float:left;font-weight:bold;width:190px;padding:1px 0 0 5px;height:17px;overflow:hidden;display:{[this.checkHideTitle()]}">{bd_subject}</div>',
                '                <div style="float:left;width:100%;padding:3px 0 3px 0;border-bottom:1px solid #eeeeee"></div>',
                '                <div style="float:left;width:100%;margin-top:5px">',
                '                    <img style="float:left;margin-top:2px" src="{[this.getFileIcon(values)]}" onerror="this.class=\'fa fa-exclamation-triangle\'">',
                '                    <span style="margin-left:5px;color:#666666;">{bd_regdate}</span><br>',
                '                    <span style="margin-left:5px;color:#666666;">{bd_name}</span>',
                '                </div>',
                '                <div class="describe" style="float:left;width:100%;height:16px;margin-top:10px;font-size:12px;overflow:hidden">{bd_content}</div>',
                '            </div>        ',
                '        </div>',
                '    </div>',
                '</tpl>   ',
                {
                    getTplLength: function(xcount) {
                        return xcount;
                    },
                    getThumbnail: function(value) {
                        var val = '';
                        if(values.bd_file[0] === undefined){
                            val = 'resources/images/ico_noimage.gif';
                        }
                        else{
                            val = values.bd_file[0].thumb_path + '/T';
                        }
                        return val;

                    },
                    getFileLength: function(value) {
                        var val = '';
                        if(!values.bd_file){
                            val = 0;
                        }
                        else{
                            val = values.bd_file.length;
                        }
                        return val;
                    },
                    checkIfImage: function(values) {
                        var files = values.bd_file;
                        if(files.length === 0) return;

                        var val = 'resources/images/ico_noimage.gif';
                        var isImage = getController('Config').isImage(files[0]);
                        if(isImage){
                            val = files[0].thumb_path;
                        }
                        return val;
                    },
                    getFileIcon: function(values) {
                        var files = values.bd_file;
                        var val = '../images/share/ico_ext/ext_no.png';
                        if(files && files[0]){
                            var fileName = files[0].file_name;
                            var tmpArr = fileName.split('.');
                            var ext = '';
                            if(tmpArr.length > 1){
                                if(window.location.hostname == 'localhost'){
                                    val = 'resources/images/ico_noimage.gif';
                                }
                                else{
                                    ext = tmpArr[tmpArr.length - 1];
                                    if(ext.trim() == 'tiff') ext = 'tif';
                                    if(ext.trim() == 'jpeg') ext = 'jpg';
                                    val = '../images/share/ico_ext/ext_'+ext+'.png';
                                }
                            }
                        }
                        return val;
                    },
                    checkHideTitle: function() {
                        var val = 'inline';
                        if(config.option.title == '0' || config.option.title == 'false'){
                            val = 'none';
                        }
                        return val;
                    }
                }
            ),
            itemSelector: 'div.gunit'
        }
    ]

});