/*
 * File: app/view/HistoryWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.HistoryWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.historywindow',

    requires: [
        'Actor.view.HistoryWindowViewModel',
        'Actor.view.HistoryWindowViewController',
        'Ext.form.field.Checkbox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column'
    ],

    controller: 'historywindow',
    viewModel: {
        type: 'historywindow'
    },
    modal: true,
    height: 768,
    itemId: 'historyWindow',
    padding: 15,
    width: 1024,
    layout: 'border',
    ghost: true,
    maximizable: true,

    items: [
        {
            xtype: 'container',
            region: 'north',
            height: 37,
            itemId: 'historyHeader',
            style: 'background-color:white;border-bottom:1px solid #cecece',
            items: [
                {
                    xtype: 'checkboxfield',
                    itemId: 'showChanged',
                    margin: '0 20 10 0',
                    style: 'float:right',
                    hideLabel: true,
                    checked: true,
                    bind: {
                        boxLabel: '{activateChanged}'
                    },
                    listeners: {
                        change: 'onShowChangedChange'
                    }
                }
            ]
        },
        {
            xtype: 'gridpanel',
            region: 'center',
            splitterResize: false,
            autoShow: true,
            flex: 1,
            itemId: 'historyGrid',
            header: false,
            title: 'My Grid Panel',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'east',
            itemId: 'historyViewer',
            scrollable: true,
            width: 490,
            collapsed: true,
            collapseDirection: 'right',
            collapsible: true,
            bind: {
                title: '{viewDocument}'
            }
        }
    ],
    listeners: {
        add: 'onHistoryWindowAdd'
    }

});