/*
 * File: app/view/LinkUnit.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.LinkUnit', {
    extend: 'Ext.container.Container',
    alias: 'widget.linkunit',

    requires: [
        'Actor.view.LinkUnitViewModel',
        'Ext.container.Container',
        'Ext.button.Button',
        'Ext.form.Label'
    ],

    config: {
        bd_idx: null
    },

    viewModel: {
        type: 'linkunit'
    },
    margin: '0 0 0 5',
    style: 'border: 1px solid #cecece',
    width: 80,
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    bind: {
        bd_idx: '{bdIdx}'
    },
    items: [
        {
            xtype: 'container',
            height: 24,
            itemId: 'header',
            style: 'text-align:right;overFlow:hidden;',
            items: [
                {
                    xtype: 'button',
                    height: 24,
                    itemId: 'delUnit',
                    margin: '2 0 0 0',
                    ui: 'plain-toolbar-small',
                    width: 24,
                    glyph: 'xf146@FontAwesome',
                    listeners: {
                        click: 'onDelUnitClick'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            height: 80,
            itemId: 'image',
            style: {
                'background-repeat': 'no-repeat',
                'background-position': 'center',
                'background-color': 'white'
            },
            width: 80
        },
        {
            xtype: 'label',
            style: 'font-size:11px',
            bind: {
                text: '{unitTitle}'
            }
        }
    ],

    onDelUnitClick: function(button, e, eOpts) {
        var unit = button.up('container').up('container');
        unit.destroy();
    },

    hideHeader: function() {
        this.down('#header').setHidden(true);
    }

});