/*
 * File: app/view/LinkedData.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.LinkedData', {
    extend: 'Ext.container.Container',
    alias: 'widget.linkeddata',

    requires: [
        'Actor.view.LinkedDataViewModel',
        'Ext.button.Button',
        'Ext.container.Container'
    ],

    viewModel: {
        type: 'linkeddata'
    },
    width: '100%',

    layout: {
        type: 'hbox',
        align: 'stretch',
        padding: '0 2 0 2'
    },
    items: [
        {
            xtype: 'button',
            height: 80,
            itemId: 'addLink',
            ui: 'plain-toolbar-small',
            width: 80,
            glyph: 'xf0fe@FontAwesome'
        },
        {
            xtype: 'container',
            layout: {
                type: 'vbox',
                align: 'stretch'
            }
        }
    ]

});