/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'Actor.view.MainViewViewModel',
        'Actor.view.MainViewController',
        'Actor.view.CategoryContainer',
        'Ext.form.Label',
        'Ext.toolbar.Spacer',
        'Ext.button.Button',
        'Ext.tab.Panel',
        'Ext.panel.Tool',
        'Ext.XTemplate'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    height: 250,
    id: 'mainView',
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'container',
            region: 'north',
            height: 45,
            hidden: true,
            id: 'headerPanel',
            style: {
                'background-color': '#252432'
            },
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    width: 240,
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    },
                    items: [
                        {
                            xtype: 'label',
                            flex: 1,
                            style: {
                                color: 'white',
                                'font-weight': 700,
                                'font-size': '16px',
                                'margin-left': '12px'
                            },
                            bind: {
                                text: '{siteName}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    id: 'shortcutBar',
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    }
                },
                {
                    xtype: 'tbspacer',
                    flex: 1
                },
                {
                    xtype: 'container',
                    height: '100%',
                    id: 'topToolbar',
                    itemId: 'topToolbar',
                    style: {
                        'background-color': '#304e7b'
                    },
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        padding: '0 10 0 10'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var newUserInfo = {};
                                Ext.Object.each(userInfo, function(key, value){
                                    newUserInfo[key] = value;
                                });


                                var obj = {};
                                obj.nv_id = userInfo.nv_id;
                                obj.nv_name = userInfo.nv_name;
                                obj.nv_phone = userInfo.nv_phone;
                                obj.nv_cellphone = userInfo.nv_cellphone;
                                obj.nv_file = userInfo.nv_file;
                                obj.nv_addr1 = userInfo.nv_addr1;
                                obj.nv_addr2 = userInfo.nv_addr2;
                                obj.nv_duty = userInfo.nv_duty;
                                obj.nv_email = userInfo.nv_email;
                                obj.nv_sex = userInfo.nv_sex;
                                obj.nv_nick = userInfo.nv_nick;


                                /* combo for selecting a gender */
                                var comboSx = Ext.create('Ext.form.ComboBox',{
                                    fieldLabel:'',
                                    store:[loc.member.male, loc.member.female]
                                });
                                ///////////////////////////////////////
                                // window for showing user informaiton//
                                ///////////////////////////////////////
                                var win = Ext.create('Ext.window.Window', {
                                    title:loc.member.profile,
                                    padding:10,
                                    layout:{
                                        type:'vbox',
                                        pack:'center'
                                    },
                                    items:[
                                    {
                                        ///////////////////////////////////////
                                        // property grid for user informaiton//
                                        ///////////////////////////////////////
                                        xtype:'propertygrid',
                                        width:400,
                                        source:obj,
                                        hideHeaders:true,
                                        customRenderers:{
                                            nv_file:function(v){
                                                var value = '<div style="width:50px;height:50px;background-image:url(\''+v+'\');background-position:center;';
                                                value    += 'background-size:cover"></div>';
                                                return value;
                                            }
                                        },
                                        customEditors:{
                                            nv_sex :comboSx
                                        },
                                        propertyNames:{
                                            nv_name:loc.member.name,
                                            nv_file:loc.member.photo,
                                            nv_id:loc.member.userId,
                                            nv_phone:loc.member.phone,
                                            nv_cellphone:loc.member.cellPhone,
                                            nv_addr1:loc.member.addr1,
                                            nv_addr2:loc.member.addr2,
                                            nv_duty:loc.member.position,
                                            nv_email:loc.member.email,
                                            nv_sex:loc.member.sex,
                                            nv_nick:loc.member.nickname,
                                        },
                                        listeners: {
                                            beforeedit: function( editor, e, opts ) {
                                                if( e.record.get('name')== 'nv_id') {//id can't modify
                                                    return false;
                                                }
                                            }
                                        }

                                    },
                                    {
                                        xtype:'container',
                                        width:'100%',
                                        padding:20,
                                        layout:{
                                            type:'hbox',
                                            pack:'center'
                                        },
                                        items:[
                                        {
                                            /////////////////////////////////
                                            // button for changing password//
                                            /////////////////////////////////
                                            xtype:'button',
                                            text:loc.member.changePassword,
                                            ui:'plain-toolbar-small',
                                            handler:function(button){
                                                /////////////////////////////////
                                                // window for changing password//
                                                /////////////////////////////////
                                                var passWin = Ext.create('Ext.window.Window', {
                                                    title:loc.member.changePassword,
                                                    layout:{
                                                        type:'vbox',
                                                        pack:'center'
                                                    },
                                                    padding:'10 20 20 20',
                                                    items:[
                                                    {
                                                        xtype:'textfield',
                                                        itemId:'fdPass',
                                                        fieldLabel:loc.login.password,
                                                        labelAlign:'top',
                                                        inputType:'password'
                                                    },
                                                    {
                                                        xtype:'textfield',
                                                        itemId:'fdNewPass',
                                                        fieldLabel:loc.member.newPassword,
                                                        labelAlign:'top',
                                                        inputType:'password'
                                                    },
                                                    {
                                                        xtype:'textfield',
                                                        itemId:'fdCheckPass',
                                                        fieldLabel:loc.member.checkNewPassword,
                                                        labelAlign:'top',
                                                        inputType:'password'
                                                    },
                                                    {
                                                        /////////////////////////////////////////
                                                        // button for save the changed password//
                                                        /////////////////////////////////////////
                                                        xtype:'button',
                                                        text:loc.member.change,
                                                        handler:function(button){
                                                            var curPass = button.up('window').down('#fdPass').getValue();
                                                            var newPass = button.up('window').down('#fdNewPass').getValue();
                                                            var chkPass = button.up('window').down('#fdCheckPass').getValue();
                                                            if(curPass.trim() === ''){
                                                                Ext.toast(loc.error.needPassword);
                                                                button.up('window').down('#fdPass').focus();
                                                                return;
                                                            }
                                                            if(newPass.trim() === ''){
                                                                Ext.toast(loc.error.needNewPassword);
                                                                button.up('window').down('#fdNewPass').focus();
                                                                return;
                                                            }
                                                            if(chkPass.trim() === ''){
                                                                Ext.toast(loc.error.needCheckPassword);
                                                                button.up('window').down('#fdCheckPass').focus();
                                                                return;
                                                            }
                                                            if(newPass != chkPass){
                                                                Ext.toast(loc.error.twoPasswordNotMatch);
                                                                return;
                                                            }

                                                            userInfo.nv_pass = newPass;
                                                            Ext.data.JsonP.request({
                                                                url:getLoginApi(),
                                                                params:{
                                                                    nv_id:sessionId,
                                                                    nv_pass:curPass
                                                                },
                                                                success:function(response){
                                                                    if(!isHtml5()){
                                                                        alert(loc.config.isNeedHtml5);
                                                                        return;
                                                                    }
                                                                    if(!response.result){
                                                                        Ext.toast(loc.error.wrongPassword);
                                                                        button.up('window').down('#fdPass').focus();
                                                                        return;
                                                                    }
                                                                    else{
                                                                        /* update by formdata */
                                                                        var fd = new FormData();
                                                                        Ext.Object.each(userInfo, function(key, value){
                                                                            fd.append(key, value);
                                                                        });

                                                                        var request = new XMLHttpRequest();
                                                                        request.open('POST', getMemberUpdateApi());
                                                                        request.onload = function(){
                                                                            if(request.status != 200){
                                                                                alert('Error " + oReq.status + " occurred when trying to update.<br \/>');
                                                                            }
                                                                            else{
                                                                                Ext.toast(loc.member.updateComplete);
                                                                                Ext.toast(loc.login.programRestart);
                                                                                setTimeout(function(){
                                                                                    Ext.getCmp('headerPanel').down('#btnLogout').fireEvent('click');
                                                                                }, 1000);
                                                                            }
                                                                        };
                                                                        request.send(fd);
                                                                    }
                                                                },
                                                                failure:function(response){
                                                                    alert('Network connection problem');
                                                                }

                                                            });
                                                        }
                                                    }
                                                    ]
                                                }).show();
                                            },
                                            listeners:{
                                                afterrender:function(button){
                                                    var bEl = button.el.select('.x-btn-inner').elements[0];
                                                    Ext.get(bEl).setStyle({color:'#5fa2dd'});
                                                }
                                            }
                                        },
                                        {
                                            /////////////////////////////////////
                                            // button for save user information//
                                            /////////////////////////////////////
                                            xtype:'button',
                                            text:loc.config.save,
                                            handler:function(button){
                                                var isChanged = false;
                                                /* check if the changed field exists */
                                                Ext.Object.each(obj, function(key, value){
                                                    if(value != userInfo[key]){
                                                        isChanged = true;
                                                        newUserInfo[key] = value;//save only changed user information to update
                                                    }
                                                });
                                                if(isChanged){//if something has changed
                                                    var passWin = Ext.create('Ext.window.Window', {
                                                        padding:'10 20 10 20',
                                                        items:[
                                                        {
                                                            xtype:'label',
                                                            text:loc.member.passwordForSecurity,
                                                            cls:'form-title-label'
                                                        },
                                                        {
                                                            xtype:'textfield',
                                                            fieldLabel:loc.login.password,
                                                            labelAlign:'top',
                                                            inputType:'password',
                                                            itemId:'fdPass'
                                                        },
                                                        {
                                                            xtype:'button',
                                                            text:loc.main.ok,
                                                            handler:function(button){
                                                                Ext.data.JsonP.request({
                                                                    url:getLoginApi(),
                                                                    params:{
                                                                        nv_id:sessionId,
                                                                        nv_pass:passWin.down('#fdPass').getValue()
                                                                    },
                                                                    success:function(response){
                                                                        if(response.result){ //if logined update the changed user information
                                                                            Ext.MessageBox.confirm('Confirm', loc.main.updateChanges, function(button){
                                                                                if(button == 'yes'){
                                                                                    if(!isHtml5()){
                                                                                        alert(loc.config.isNeedHtml5);
                                                                                        return;
                                                                                    }

                                                                                    /* update by formdata */
                                                                                    var fd = new FormData();
                                                                                    Ext.Object.each(newUserInfo, function(key, value){
                                                                                        fd.append(key, value);
                                                                                    });

                                                                                    var request = new XMLHttpRequest();
                                                                                    request.open('POST', getMemberUpdateApi());
                                                                                    request.onload = function(){
                                                                                        if(request.status != 200){
                                                                                            alert('Error " + oReq.status + " occurred when trying to update.<br \/>');
                                                                                        }
                                                                                        else{
                                                                                            userInfo = newUserInfo;
                                                                                            Ext.toast(loc.member.updateComplete);
                                                                                            passWin .close();
                                                                                            win.close();
                                                                                        }
                                                                                    };
                                                                                    request.send(fd);
                                                                                }
                                                                            });                                        }
                                                                            else{
                                                                                Ext.toast(loc.login.loginInfo);
                                                                            }
                                                                        },
                                                                        failure:function(response){
                                                                            alert('Network connection problem');
                                                                        }

                                                                    });
                                                                }
                                                            }
                                                            ]

                                                        }).show();
                                                    }
                                                    else{//nothing has been changed
                                                        Ext.toast(loc.member.updateComplete);
                                                        win.close();
                                                    }
                                                }
                                            }
                                            ]
                                        }

                                        ]
                                    }).show();

                            },
                            itemId: 'btnUser',
                            ui: 'plain-toolbar-small',
                            iconCls: 'fa fa-user',
                            bind: {
                                tooltip: '{userInfo}'
                            }
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                getController('Work').selectMember('', 'textMessage');
                            },
                            itemId: 'btnUsers',
                            ui: 'plain-toolbar-small',
                            iconCls: 'fa fa-book',
                            bind: {
                                tooltip: '{userList}'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnLogout',
                            ui: 'plain-toolbar-small',
                            iconCls: 'fa fa-sign-out',
                            bind: {
                                tooltip: '{logout}'
                            },
                            listeners: {
                                click: 'onBtnLogoutClick'
                            }
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'btnGoPd',
                            ui: 'plain-toolbar-small',
                            iconCls: 'fa fa-home',
                            listeners: {
                                click: 'onBtnGoPdClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnVertion',
                            ui: 'plain-toolbar-small',
                            iconCls: 'fa fa-info',
                            listeners: {
                                click: 'onBtnVersionClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            sales: [
                
            ],
            region: 'west',
            split: true,
            hidden: true,
            id: 'westPanel',
            style: {
                'border-right': '1px solid #cfd3d6'
            },
            width: 240,
            collapseDirection: 'left',
            collapsible: true,
            header: false,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            bind: {
                title: '{category}'
            },
            items: [
                {
                    xtype: 'categorycontainer',
                    flex: 1
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            hidden: true,
            id: 'centerPanel',
            layout: 'border',
            collapseFirst: false,
            collapsible: false,
            header: false,
            title: 'Center',
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel',
                    layout: 'border',
                    header: false,
                    items: [
                        {
                            xtype: 'container',
                            region: 'north',
                            height: 70,
                            id: 'mainIconPanel',
                            style: {
                                'background-color': '#304e7b'
                            },
                            layout: {
                                type: 'hbox',
                                padding: '0 0 0 20'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnNew',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-file-o',
                                    scale: 'medium',
                                    bind: {
                                        text: '{newPost}'
                                    },
                                    listeners: {
                                        click: 'onBtnNewClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCopy',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-clone',
                                    scale: 'medium',
                                    bind: {
                                        text: '{copy}'
                                    },
                                    listeners: {
                                        click: 'onBtnCopyClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnEdit',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-pencil-square-o',
                                    scale: 'medium',
                                    bind: {
                                        text: '{edit}'
                                    },
                                    listeners: {
                                        click: 'onBtnEditClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnRemove',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-trash-o',
                                    scale: 'medium',
                                    bind: {
                                        text: '{remove}'
                                    },
                                    listeners: {
                                        click: 'onBtnRemoveClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnDownload',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-download',
                                    scale: 'medium',
                                    bind: {
                                        text: '{download}'
                                    },
                                    listeners: {
                                        click: 'onBtnDownloadClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnComment',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-commenting-o',
                                    scale: 'medium',
                                    bind: {
                                        text: '{newComment}'
                                    },
                                    listeners: {
                                        click: 'onBtnCommentClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnRecent',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-eye',
                                    scale: 'medium',
                                    bind: {
                                        text: '{recentItem}'
                                    },
                                    listeners: {
                                        click: 'onBtnRecentClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnColorway',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'colorway',
                                    scale: 'medium',
                                    bind: {
                                        hidden: '{!useColorway}',
                                        text: '{colorway}'
                                    },
                                    listeners: {
                                        click: 'onBtnColorwayClick',
                                        render: 'onBtnColorwayRender'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnMapping',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-female',
                                    scale: 'medium',
                                    bind: {
                                        hidden: '{!useMapping}'
                                    },
                                    listeners: {
                                        click: 'onBtnMappingClick',
                                        afterrender: 'onBtnMappingAfterRender'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSearch',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-search',
                                    scale: 'medium',
                                    bind: {
                                        text: '{search}'
                                    },
                                    listeners: {
                                        click: 'onBtnSearchClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'mainBtnComapre',
                                    style: 'color:white',
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-files-o',
                                    scale: 'medium',
                                    listeners: {
                                        render: 'onMainBtnComapreRender',
                                        click: 'onMainBtnComapreClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnMessage',
                                    style: {
                                        color: 'white'
                                    },
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    iconAlign: 'top',
                                    iconCls: 'fa fa-share-square-o',
                                    scale: 'medium',
                                    bind: {
                                        text: '{sendingDoc}'
                                    },
                                    listeners: {
                                        click: 'onBtnMessageClick'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    height: '100%',
                                    itemId: 'displayCon',
                                    layout: 'vbox',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 28,
                                            padding: '12 0 10 17',
                                            style: 'color:white;font-size:11px',
                                            listeners: {
                                                render: 'onLabelRender'
                                            }
                                        },
                                        {
                                            xtype: 'container',
                                            height: '100%',
                                            padding: '3 0 0 5',
                                            layout: {
                                                type: 'hbox',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbspacer',
                                                    height: '38%',
                                                    style: {
                                                        'border-right': '1px solid #ffffff',
                                                        opacity: 0.5
                                                    },
                                                    width: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnGallType',
                                                    style: {
                                                        color: 'white'
                                                    },
                                                    ui: 'plain-toolbar-small',
                                                    width: 40,
                                                    glyph: 'xf009@FontAwesome',
                                                    bind: {
                                                        tooltip: '{galleryMode}'
                                                    },
                                                    listeners: {
                                                        click: 'onBtnGallTypeClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnTxtType',
                                                    style: {
                                                        color: 'white'
                                                    },
                                                    ui: 'plain-toolbar-small',
                                                    width: 40,
                                                    glyph: 'xf039@FontAwesome',
                                                    bind: {
                                                        tooltip: '{textMode}'
                                                    },
                                                    listeners: {
                                                        click: 'onBtnTxtTypeClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnListType',
                                                    style: {
                                                        color: 'white'
                                                    },
                                                    ui: 'plain-toolbar-small',
                                                    width: 40,
                                                    glyph: 'xf0ca@FontAwesome',
                                                    bind: {
                                                        tooltip: '{combineMode}'
                                                    },
                                                    listeners: {
                                                        click: 'onBtnListTypeClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnChipType',
                                                    style: {
                                                        color: 'white'
                                                    },
                                                    ui: 'plain-toolbar-small',
                                                    width: 40,
                                                    iconCls: 'fa fa-th',
                                                    bind: {
                                                        hidden: '{!isColorChip}',
                                                        tooltip: '{colorChip}'
                                                    },
                                                    listeners: {
                                                        click: 'onBtnChipTypeClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    height: '38%',
                                                    style: {
                                                        'border-right': '1px solid #ffffff',
                                                        opacity: 0.5
                                                    },
                                                    width: 1
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'mainBtnGroup',
                                    style: 'color:white',
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    glyph: 'xf022@FontAwesome',
                                    iconAlign: 'top',
                                    scale: 'medium',
                                    bind: {
                                        hidden: '{isGallery}',
                                        text: '{byGroup}'
                                    },
                                    listeners: {
                                        click: 'onMainBtnGroupClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'mainBtnChart',
                                    style: 'color:white',
                                    ui: 'plain-toolbar-medium',
                                    width: 70,
                                    glyph: 'xf022@FontAwesome',
                                    iconAlign: 'top',
                                    scale: 'medium',
                                    bind: {
                                        hidden: '{!needSum}',
                                        text: '{chart}'
                                    },
                                    listeners: {
                                        click: 'onMainBtnChartClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            region: 'center',
                            itemId: 'listTab'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    split: true,
                    cls: 'southpanel',
                    flex: 0.7,
                    hidden: true,
                    itemId: 'southPanel',
                    scrollable: true,
                    collapsible: true
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'east',
            split: true,
            id: 'eastPanel',
            width: 1,
            layout: 'border',
            animCollapse: false,
            bodyStyle: {
                'background-color': 'white'
            },
            collapseDirection: 'right',
            collapseFirst: false,
            collapsible: true,
            title: 'East',
            titleCollapse: false,
            tools: [
                {
                    xtype: 'tool',
                    margin: '0 8 0 0',
                    id: 'icoEditable',
                    itemId: 'editable',
                    iconCls: 'fa fa-lock',
                    listeners: {
                        render: 'onEditalbeRender',
                        click: 'onEditalbeClick'
                    }
                },
                {
                    xtype: 'tool',
                    margin: '0 8 0 0',
                    hidden: true,
                    itemId: 'history',
                    iconCls: 'fa fa-history',
                    listeners: {
                        render: 'onHistoryRender'
                    }
                },
                {
                    xtype: 'tool',
                    margin: '0 8 0 0',
                    itemId: 'print',
                    iconCls: 'fa fa-print',
                    listeners: {
                        render: 'onPrintRender',
                        click: 'onPrintClick'
                    }
                },
                {
                    xtype: 'tool',
                    margin: '0 8 0 0',
                    itemId: 'changForm',
                    iconCls: 'fa fa-file-text-o',
                    listeners: {
                        render: 'onChangFormRender',
                        click: 'onChangFormClick'
                    }
                },
                {
                    xtype: 'tool',
                    margin: '0 8 0 0',
                    itemId: 'slideShow',
                    iconCls: 'fa fa-slideshare',
                    listeners: {
                        render: 'onSlideShowRender',
                        click: 'onSlideShowClick'
                    }
                },
                {
                    xtype: 'tool',
                    margin: '0 8 0 0',
                    hidden: true,
                    itemId: 'sendEmail',
                    iconCls: 'fa fa-envelope-o',
                    listeners: {
                        render: 'onSendEmailRender',
                        click: 'onSendEmailClick'
                    }
                },
                {
                    xtype: 'tool',
                    margin: '0 8 0 0',
                    itemId: 'colorwaySmall',
                    iconCls: 'colorway-small',
                    bind: {
                        hidden: '{!useColorway}'
                    },
                    listeners: {
                        render: 'onColorwaySmallRender',
                        click: 'onColorwaySmallClick'
                    }
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    flex: 2,
                    region: 'north',
                    id: 'viewPanel',
                    scrollable: 'y',
                    bodyPadding: '15 0 0 0',
                    listeners: {
                        add: 'onViewPanelAdd'
                    }
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'commentPanel',
                    itemId: 'commentPanel',
                    scrollable: true,
                    tpl: [
                        '<tpl for=".">',
                        '    <div style="width:100%;border:1px solid #cccccc;padding:10px;margin:0 auto 5px;background-color:#ffffff">',
                        '        <div style="border-bottom:1px dotted #cccccc;">',
                        '            <span style="font-weight:bold">Name</span>: {cmt_name} ',
                        '            <span style="font-weight:bold;margin-left:20px">Date</span>: {cmt_regdate}',
                        '            <div style="float:right;">',
                        '                <i class="fa fa-trash" style="cursor:pointer;" onclick="getController(\'Main\').removeComment({cmt_idx})"></i>',
                        '            </div>',
                        '        </div>',
                        '        <div style="width:100%;margin-top:5px">',
                        '            {cmt_content}',
                        '        </div>          ',
                        '    </div>',
                        '</tpl>'
                    ],
                    animCollapse: false,
                    bodyPadding: 10,
                    bodyStyle: {
                        'background-color': '#FBFDFF'
                    },
                    collapsed: false,
                    collapseDirection: 'bottom',
                    collapsible: true,
                    bind: {
                        title: '{commentList}'
                    },
                    tools: [
                        {
                            xtype: 'tool',
                            itemId: 'addComment',
                            iconCls: 'fa fa-plus-circle',
                            listeners: {
                                afterrender: 'onAddCommentAfterRender',
                                click: 'onAddCommentClick'
                            }
                        }
                    ],
                    listeners: {
                        render: 'onCommentPanelRender'
                    }
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onMainViewBeforeRender',
        resize: 'onMainViewResize'
    }

});