/*
 * File: app/view/Shortcut.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.Shortcut', {
    extend: 'Ext.container.Container',
    alias: 'widget.shortcut',

    requires: [
        'Actor.view.ShortcutViewModel',
        'Actor.view.ShortcutViewController',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.form.Label'
    ],

    controller: 'shortcut',
    viewModel: {
        type: 'shortcut'
    },
    style: 'cursor:pointer',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'button',
            itemId: 'shortcutButton',
            overCls: 'shortcut-hover',
            listeners: {
                click: 'onShortcutButtonClick'
            }
        },
        {
            xtype: 'tbspacer',
            height: 10
        },
        {
            xtype: 'label',
            itemId: 'shortcutTitle',
            style: 'text-align:center;cursor:pointer',
            width: '100%'
        }
    ],
    listeners: {
        afterrender: 'onContainerAfterRender'
    },

    setButtonStyle: function(style) {
        var btn = this.down('button');
        btn.setUI('plain');
        btn.setStyle(style);
    },

    setIcon: function(ico) {
        this.down('button').setIconCls('fa fa-' + ico);
    },

    setTitle: function(text) {
        var titleCon = this.down('#shortcutTitle');
        titleCon.setStyle('color', 'white');
        titleCon.setText(text);
    }

});