/*
 * File: app/view/UploadWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.UploadWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.uploadwindow',

    requires: [
        'Actor.view.UploadWindowViewModel',
        'Actor.view.UploadWindowViewController'
    ],

    config: {
        target: null
    },

    controller: 'uploadwindow',
    viewModel: {
        type: 'uploadwindow'
    },
    modal: true,
    itemId: 'uploadWindow',
    width: 700,
    closeAction: 'hide',
    ghost: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    listeners: {
        afterlayout: 'onUploadWindowAfterLayout'
    },

    setTarget: function(grid) {
        this.target = grid;
    }

});