/*
 * File: app/view/UploadStatusWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.UploadStatusWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.uploadstatuswindow',

    requires: [
        'Actor.view.UploadStatusWindowViewModel',
        'Ext.container.Container',
        'Ext.XTemplate',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'uploadstatuswindow'
    },
    modal: true,
    padding: 20,
    scrollable: true,
    width: 400,
    ghost: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    bind: {
        title: '{uploading}'
    },
    items: [
        {
            xtype: 'container',
            itemId: 'statuses',
            tpl: [
                '<tpl for=\'.\'>',
                '    <div style="float:left;width:100%;margin-top:10px">',
                '        <div style="float:left;width:100%">{file.name}</div>',
                '        <div style="float:left;height:16px;width:100%">',
                '            <div id="bar_{file.id}" style="width:1%;height:100%;border 1px solid #cecece;background-color:#c3dff8;color:white;font-size:10px;text-align:center"></div>',
                '        </div>',
                '    </div>',
                '</tpl>'
            ],
            width: '100%'
        },
        {
            xtype: 'container',
            margin: '20 0 0 0',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnCancelUpload',
                    glyph: 'xf00d@FontAwesome',
                    bind: {
                        text: '{cancel}'
                    }
                }
            ]
        }
    ]

});