/*
 * File: app/view/Viewer.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Actor.view.Viewer', {
    extend: 'Ext.container.Container',
    alias: 'widget.viewer',

    requires: [
        'Actor.view.ViewerViewModel',
        'Actor.view.ViewerViewController'
    ],

    config: {
        categoryId: '',
        info: null,
        editable: false
    },

    controller: 'viewer',
    viewModel: {
        type: 'viewer'
    },
    cls: 'viewer',
    height: '100%',
    itemId: 'viewer',

    listeners: {
        afterrender: 'onViewerAfterRender'
    }

});