var languageSet = {
    English:{
        config:{
            addMember:'Add member',
            addShortcut:'Add Shortcut',
            apply:'Apply',
            changeShortcut:'Change icon',
            chooseIcon:'Select a target category and choose an icon to apply',
            combineMode:'Combine mode',
            configEditorTitle:'Set the file category that is used for Html editor',
            configEditorText:'Choose a category which will be saved uploaded files at Html Editor, it can be activated "Add file" button',            
            deleltedShortcut:'It is a deleted shortcut, It will be remvoed at the list',
            delShortcut:'Delete Shortcut',
            detailMode:'Detail list',
            digitNumber:'digit number',
            displayAsImage:'Display as an Image',
            existShortcut:'It already has been added as a shorcut',
            fieldSetting:'Field setting',
            hexField:'It will be transferd to a color cell when input a hex value(#FFCC00)',
            hexTitle:'Render to a color chip',            
            galleryMode:'Galllery Mode',
            getRecordTitle:'Copy a value from another field and share the record',
            getRecordExp:'Copy a value which saved in another category and share the selected record for fill automatically into another fields',   
            getValueTitle:'Copy a value from another field',
            hide:'Hide',
            hideDefaultField:'Do not use the default fields like title, text content and attached',
            hideField:'Hiding field',
            imageWithURL:'Type a image url to display the image',            
            itemListNum:'Number of items per page(Enter to apply)',
            initShortcut:'Inint. Shortcut',
            isNeedHtml5:'The browser that supports HTML5 needed to use this function',
            listDisplay:'How to show the data list',
            membersJob:'Member responsibility',
            needApprovalSetting:'It must configured the approval step in PD',
            needMemberFields:'It must configured fields that the codes are "image", "userName", "duty", "department", "phone", "email" and "job"',
            needRestart:'(It requires restarting the program)',
            needToFrom:'It must be configured two of "to" and "from" field codes in PD',
            noCategorySelect:'Please select a category first',
            numberFormat:'Number format(ex:123456.789)',
            onlyViewOwners:'Only data that current user has uploaded will be displayed.',
            percentField:'It will be rendered a vertical graph when type a number',
            percentTitle:'Show as a percent progress bar',            
            save:'Save',
            scheduleMode:'Schedule mode',
            selectForm:'Select a form for current category',
            selectIdxPrefixField:'Select a field that is used in the auto numbering field',
            selectIdxText:'It will replace the letters as many as the number of "?" that was configured at PD',
            setIcon:'Icon setting',
            setMustSeeUser:'Setting for users who must see the list',
            settingCategory:'Setting Category',
            settingForm:'Setting the default form',
            setShortcut:'Setting shortcuts',
            show:'Show',
            showApprovalBox:'Show approval box on the top of the form',
            showAsSchedule:'Show list as a schedule table',
            showImageTitle:'If select on of option, it shows with an image',
            showSum:'Show sum',
            showSumTitle:'Sum will be displayed when the list is grouped by field',
            simpleMode:'Simple list',
            textMode:'Text Mode',
            use:'Use',
            useAsUserList:'Use the category for show user list',
            useColorTag:'Use Color tag',
            userInfo:'User profile',
            userList:'User list',
            useSimpleList:'Use simple view of data list',
            unavailableShared:'It is unavailable at a shared field.',
            viewCategory:'Hide categories at start',
            viewedListNum:'Number of items at Recently viewed list(Enter to apply)',
            viewInformation:'Keep information window visible',
            viewOrAll:'All list/Unread list'
        },
        error:{
            downloadLimit:'To download all attached files you must use the chrome browswer.<br>It will download only the first file',
            hasNoColorDataCategory:'The files in this category has no color data',
            lowerLevelToCopy:'Sorry, You have no permission to copy',
            lowerLevelToDelete:'Sorry, You have no permission to delete',
            lowerLevelToDownload:'Sorry, You have no permission to download',
            lowerLevelToEmail:'Sorry, You have no permission to send the e-mail',
            lowerLevelToPrint:'Sorry, You have no permission to print',
            lowerLevelToWrite:'Sorry, You have no permission to write or edit',
            mailError:'Email could not be sent because something wrong while sending it',
            needCheckPassword:'Type new pass world once more',
            needPassword:'Current password required to update',
            needNewPassword:'Type new password',
            needSharp:'The first chractor must be "#"',
            noImage:'Image can not find',
            noCategory:'The category has been removed or nonexistent, Program will restart automatically',
            noColorchipCategory:'This category is not for colorchips',
            noMangerMail:"The manager's email is not configured or incorrect. <br> it requires to send the email",
            noSelectedField:'A field is not selected',
            noSession:'It looks lost the connection because its not used for long time, please log in again',
            noSubcategory:'It seems not to create sub categories that required for the selected item were removed. please ask to administrator to fix it \nError code:101',
            notImageFile:'Selected file is nat available image format',
            notUser:'It is not existing user',
            optionError:'An error found in setting for field or category option\nError code:109',
            overContactFields:'The contact field never used twice please contact your administrator\nError code:102',
            removeGetRecord:'The below option has configured. It can not be used at the same time',
            removeGetValue:'The above option has configured. It can not be used at the same time',
            removeImpossible:'It can remove only from the source category in case of a clone category<br>Sorce category:',
            typeNotMatch:'It can not be copied because the field type is not the same with soruce',
            twoPasswordNotMatch:'New password is not match, please type again',
            unknwonColor:'It is unknown color',
            wrongPassword:'You entered a wrong password'
        },
        login:{
            initShortcut:'Reset shortcuts',
            loginInfo:'The ID or the password is incorrect',
            login:'LOGIN',
            logout:'Log out',
            password:'Password',
            programRestart:'You need to log in again with new password',
            userId:'User ID'
        },
        main:{
            add:'Add',
            attachFile:'Attachment',
            basicInfo:'Basic info.',
            browse:'Browse',
            canceled:'Canceled',
            category:'Category',
            caution:'Caution',
            colortag:'Color tag',
            commentList:'Comment list',
            compareData:'Comparing data',
            complete:'Save',
            config:'Preference',
            connectedCategory:' category is connected to this category',
            contentTitle:'Description:',
            copied:'copy complete',
            copyMessage:'Data will be copied to selected category. Are you sure',
            default:'Default',
            delAlert:'Are you sure? It can not be recovered',
            delAll:'Delete all of the selected files',
            deleteComplete:'Remove complete',
            deleteData:'Deleting data',
            department:'Department',
            description:'Description:',
            download:'Download',
            dropHere:'Double click or drag and drop here to link',
            duplicated:'This data has been already added',
            editable:'Activated editing mode, click an item to edit',
            editDay:'Edited day',
            email:'E-mail',
            emailNotify:'The e-mail will be automatically sent the information of selected data, you may add a comment<br>You may add a recipient separating by ","',
            emptyItem:'Select one',
            file:'File',
            gridTitle:'Data list',
            historyList:'Version List',
            item:'Item(s)',
            lastModifyBy:'Edited by',
            loadingImage:'Image is loading. Please wait a moment',
            mailComplete:'The email has been sent complete',
            message:'Message',
            name:'Name',
            networkProblem:'Network connection has a problem',
            newComment: 'Leave comment',             
            no:'No',
            noComment:'You comment nothing',
            noData:'No data found in this category',
            noFile:'No file to download.',
            noPermission:'You have no permission to delete or edit it',
            nothingtoSend:'No item selected to send the email',
            nothingToPrint:'Nothing selcectd to print',
            notice:'Notification',
            ok:'OK',
            onlyNumber:'It allows only with numbers ',
            permissionError:'Permission Error',
            phone:'Phone',
            pluginIntro:'Click an item that you want to see the details from the list',
            preview:'View',
            printIt:'Print',
            refImageTitle: 'Attachement',
            refresh:'Refresh',
            regDate:'Date',
            reset:'Reset',
            saveByNewDesign:'Are you sure?<br> It will be saved as new design with new colorway',
            saveClose:'Save and Close',
            saveDesign:'Save design',
            saving:'Saving...',
            selectedItems:'Number of selected items',
            selectOnlyOne:'You must select only one item to do',
            selectValue:'Select a value',
            showImage:'Show image',
            showOffice:'Show Doc.',
            submitComment:'Submit',
            title:'Title',
            total:'Total',
            typeHex:'Type Hex code',            
            updateChanges:'Are you sure you want to update the changes',
            updateDesign:'Are you sure?<br>It will be replaced by new colorway and it can not be recovered',
            user:'User',
            yes:'Yes'
        },
        member:{
            addr1:'Address 1',
            addr2:'Address 2',
            birthday:'Birthday',
            cellPhone:'Mobile phone',
            change:'Change',
            changePassword:'Change Password',
            checkNewPassword:'Retype the new password',
            email:'Email',
            female:'Female',
            male:'Male',
            name:'Name',
            passwordForSecurity:'Enter your password for security',
            newPassword:'New password',
            nickname:'Nick name',
            phone:'Telephone',
            photo:'Photo',
            position:'Position',
            profile:'Profile',
            sex:'Sex',
            task:'Task',
            title:'Title',
            updateComplete:'User profile has saved complete',
            userId:'ID'
        },        
        menu:{
            byGroup:'Display by group',
            cc:'CC',
            changeForm:'Change form',
            chart:'Chart',
            clear:'Clear',
            close:'Close',
            colorChip:'ColorChip',
            colorway:'Colorway',
            copy:'Copy',
            copyToClipboard:'Copy the link address to the clipboard',
            copyToCurrentCategory:'Copy to current category',
            download:'Download attached',
            edit:'Edit',
            editable:'Editable/Uneditable',
            facebook:'Post to facebook',
            fromAnotherDesign:'Get colorway',
            getERPData:'Get colorways from ERP',
            history:'Version',
            isEditable:'Activate editing mode',
            layoutType:'List layout',
            mapping:'Mapping',
            menu:'Menu',
            newPost:'New',
            newColorway:'New colorway',
            next:'Next',
            notice:'Notification',
            print:'Print selected',
            printInfo:'Print Information',
            recentItem:'Viewed Item',
            recipient:'To',
            remove:'Remove',
            reply:'Reply',
            restore:'Restore',
            saveAsNew:'Save as new',
            seeDetail:'See details',
            sendEmail:'Sending Email',
            setting:'Setting',
            slideshow:'Slideshow',
            today:'Today',
            uneditable:'Deactivate editing mode',
            update:'Update'
        },
        message:{
            agree:'Agree',
            agreement:'Agreement',
            allowEdit:'Allow the document editing',
            approval:'Approval',
            approvalRequest:'Approval', 
            approved:'You already approved this document',
            checkAgree:'Agreed',
            checkApproval:'Apprved',
            checkConfirm:'Confirmed',
            checkInterval:'Checking interval of new message(needs refresh by F5)',
            complete:'Message has been sent',
            confirm:'Confirm',
            confirmation:'Confirmation',   
            date:'Date',
            deleteMessages:'The selected messages will be deleted. Are you sure?',
            didAgree:'You have agreed this document',
            didApproval:'You have approved this docuemnt',
            didConfirm:'You have confirmed this document',            
            docIndex:'Docu Id',
            documentBox:'Document box',
            documentIn:'Inbox',
            documentOut:'Outbox', 
            messageBox:'Message box',
            messageIn:'Inbox',
            messageType:'Type of request',
            messageOut:'Outbox',  
            needApproval:'This document requires the approval, click the box below which for you',
            needAgree:'This document requires the agreement, click the button to agree',
            needConfirm:'This document requires the confirmation, click the button to confirm',
            noMessage:'No message found',
            normal:'Normal',
            noPermission:'You have no the reading permission, please ask to the administrator',
            noTarget:'No recipient found',   
            noUse:'Disable',
            okAgree:'This document has been agreed',
            okApproval:'This document has been approved',
            okConfirm:'This document has been confirmed',
            opened:'Read',
            readDate:'Read',
            readBy:'Read By',
            reciever:'Recipient',
            selectReciever:'Select receiver',
            selectType:'Select type of request',
            sender:'Sender',
            sendingDoc:'Send document',
            sendingMessage:'Send message',
            sentRecent:'Choose one among the people who has contacted recently',    
            statusAgree:'Agreement',
            statusApproval:'Approval',
            statusConfirm:'Confirmation',
            time30:'30 seconds',
            time5m:'5 minutes',
            time30m:'30 minutes',
            time60m:'1 hour',
            unAvailableUser:'This user has no permission to read this data',
            unread:'Unread',
            writeMessage:'Write message'
        },
        program:{
            about:'About program',
            contact:'Contact',
            currentLicense:'GPLv3',
            currentVersion:'2.0',
            email:'master@dipol.co.kr',
            license:'License',
            programName:'Program name',            
            version:'Version'

        },
        search:{
            byKeyword:'Search by keyword',
            byOutput:'Select content',
            categoryName:'Category Name',
            detailSearch:'Detail Search',
            date:'Date',
            fieldSearch:'Field Search',
            findSimilar:'Find similar colors',
            from:'From',
            fromAll:'With all categroy',
            fromCurrent:'Within selected category',
            fromEdited:'in edited items',
            fromSourceCategory:'in unedited data',            
            inWork:'Search of work',
            inWorkContent:'Search in contents of work',            
            month:'Month',
            monthly:'By year/By Month',
            nothingToSearch:'Noting to search',
            noValues:'None of condition given to search',
            search:'Search',
            searchAll:'Search through all category',
            searchOption:'Search option',
            searchResult:'Search Result',
            to:'To',
            year:'Year',
            yearRequired:'Select year first'
        },
        upload:{
            addAttachFile:'Added file', //Label for attatchment sector
            addFile:'Add file', // Button text for attaching file
            addReferFile:'Add reference file',
            addRow:'Add a row',
            attachedFile:'Attached File:',
            autoText:'Input a letter that included',
            cancel:'Cancel',
            cellEditTip:'Press Enter key to apply after typing',
            datagrpTitle:'Select a related data',
            delRow:'Remove the selected row',
            delAllRow:'Remove all row',
            dblclickToDel:'To remove a attached file, double click on it',
            edit:'Edit',
            edited:'It updated successfully',
            entry:'Insert',
            extractingColor:'Please wait extracting colors',
            fileName:'File name',
            fileSize:'File size',
            image:'Image',
            imageTooBig:'Image size is too big to display. It will show by small size or download it',
            insertFile:'Insert file{s} to content',
            imageURL:'(Image URL)',
            linkWindowTitle:'Select a data for linking',
            modified:'Last Modified',
            newEditor:'By separated editor',
            noMoreDel:'No more column to delete',
            noneSelected:'Nothing is selected to do',
            noSelectedAction:'None of Action selected',
            numOfColors:'Number of colors',
            numericOnly:'Numeric only',
            option1:'1st option',
            option2:'2nd option', 
            pleaseWait:'Plese wait while uploading...',
            posted:'Submit complete',
            readOnly:'(Read only)',
            saved:'Saving complete',
            saveHistory:'Add new version',
            savedAsUpdatedList:'Edited history will be saved',
            select:'Select',
            selectCategory:'Select a category',
            selectData:'Select item',
            selectFirstOption:'Please select the first option',
            selectSecondOption:'Are you sure that uploading without the second option?',            
            submit:'Submit',
            uploading:'Uploading...',
            uploadTitle:'New Post',
            uploadTitleInEdit:' - Edit Post'
        }, 
        viewer:{
            activateChanged:'Show changed',
            additionalInfo:'Added Info',
            approval:'Approval',
            approveCancel:'Will you cancel this approval?',
            approveDocu:'Will you approve this document?',
            byImage:'By Image',
            cannotDirectModify:'This item cannot modity directly',
            cantChangeForm:'Selected form is unavailable for this category',
            commentDeleted:'One of comments removed',
            copyToClipboard:'Press Ctrl+C to copy url to clipboard',
            detailView:'Details',
            formNeedDbgrp:'Data group field required to use this form, ask administrator to use it',
            gallery:'Gallery',
            html:'Html',
            imageList:'Image list',
            information:'Program',
            invoice:'Invoice',
            newCommentAdded:'New comment added.',
            noForm:'The configured form is not exist.',
            noRecipient:'Please specify at least one recipient.',
            normalView:'Normal',
            noPower:'You do not have enough permissions',
            noShowData:'This data has no slide show item',
            nothingToDisplay:'Nothing found to display',
            open:'Open',
            problemInData:'A problem found in value',
            recentlyViewed:'Item list recently viewed',
            selectItemFirst:'Nothing is selected to view',
            send:'Send',
            sendbyEmail:'Send by email',
            simpleList:'Simple list',
            showAttachImage:'If the attached file is an image, insert image into the content ',
            unavailableForm:'This form cannot use for current category, it needs a configuration by administrator',
            viewDocument:'View Document',
            withAttached:'including attached files',
            withCompanyInfo:'Show the logo and company information at a bottom',
            withRegister:'Show registered by',
            withRegistDay:'Show registered day',
            wrongForm:'A wrong form configuration found for current category, please ask to administrator'
        },
        work:{
            activityList:'Activity List',
            addNew:'Create new',
            contentOutput:'Output',
            contentReport:'Report',
            contentService:'Customer request',
            createNewActivity:'Create New Activity',
            deleteActivity:'Delete',
            deleteActivityTitle:'Deleting work activity',
            directInput:'Manually Enter',
            loading:'loading...',
            tabNotSelected:'One of tab must be selected',
            onlyMine:'Display only created by me',
            position:'Position',
            seeActContent:'Activities',
            seeActivity:'Sales activity',
            seeMore:'Load next page',
            workChance:'Overview',
            worklistTitle:'Work list',
            updateActivity:'Update'
        }        
    },
    Korean:{
        config:{
            addMember:'구성원 추가',
            addShortcut:'바로가기 추가',
            apply:'적용',
            changeShortcut:'아이콘 변경',
            chooseIcon:'먼저 카테고리를 선택하고 적용할 아이콘을 클릭하세요.',
            combineMode:'조합형',
            configEditorTitle:'HTML 에디터에서 등록되는 파일이 저장될 카테고리',
            configEditorText:'확장된 HTML 에디터에서 첨부되는 파일이 저장될 카테고리를 선택합니다. 설정되면 파일추가 버튼이 활성화됩니다.',             
            deleltedShortcut:'삭제된 바로가기 입니다. 목록에서 삭제 됩니다.',
            delShortcut:'바로가기 삭제',
            detailMode:'자세히',
            digitNumber:'자리 숫자',
            displayAsImage:'이미지로 표시', 
            existShortcut:'이미 바로가기에 있습니다.',
            fieldSetting:'필드 설정',
            galleryMode:'갤러리형',
            getRecordTitle:'다른 필드의 값을 복사하고 해당 레코드를 다른 필드에 공유',
            getRecordExp:'다른 카테고리 내에 저장된 특정 필드의 값을 복사하고 같은 레코드를 사용하는 다른 필드에 자동으로 복사 될수 있도록 공유합니다.',    
            getValueTitle:'다른 필드의 값을 복사',
            hexField:'칼라의 Hex 값(#FFCC00)을 입력하면 해당 색으로 변환, 표시 됩니다.',
            hexTitle:'칼라상자로 표시',            
            hideField:'필드를 보이지 않게 처리합니다.',
            imageWithURL:'이미지 주소를 입력하면 이미지로 표시 됩니다.',            
            hide:'숨김',
            hideDefaultField:'제목, 내용, 첨부파일 같은 기본 내용 필드를 사용하지 않음',
            itemListNum:'한 페이지당 항목 수(입력 후 Enter를 치면 저장 됩니다)',
            initShortcut:'바로가기초기화',
            isNeedHtml5:'HTML5를 지원하는 브라우저에서만 사용 가능한 기능입니다.',
            listDisplay:'자료목록 표시방법',
            membersJob:'업무구성',
            needApprovalSetting:'PD에서 결재란이 설정 되어 있어야 사용가능합니다.',
            needMemberFields:'PD의 카테고리설정에서 "image", "userName", "duty", "department", "phone", "email", "job" 등의 필드코드가 정의 돼 있어야 합니다.',
            needRestart:'(프로그램 재시작이 필요합니다)',
            needToFrom:'PD의 카테고리 설정에서 "to"와 "from" 두개의 필드코드가 정의 돼 있어야 합니다.',
            noCategorySelect:'선택된 카테고리가 없습니다.',
            numberFormat:'숫자형식(예:123456.789)',
            onlyViewOwners:'현재 로그인한 사용자가 등록한 데이터만 목록에 표시 됩니다.',
            percentField:'숫자를 입력하면 가로 막대 그래프로 변환하여 표시 됩니다.',
            percentTitle:'퍼센트 그래프로 표시',            
            save:'저장',
            scheduleMode:'일정표형',
            selectForm:'현재 카테고리 양식 선택',
            selectIdxPrefixField:'자동 증가 번호 필드 내에 입력될 필드 선택',
            selectIdxText:'선택된 필드의 값으로 PD에서 설정된 접두사에 포함된 "?"의 갯수 만큼 글자가 교체 됩니다.',            
            setIcon:'아이콘 설정',
            setMustSeeUser:'카테고리 자료목록을 반드시 확인해야하는 사용자 설정',
            settingCategory:'카테고리 설정',
            settingForm:'기본 양식 설정',
            setShortcut:'바로가기설정',
            show:'표시',
            showApprovalBox:'양식에 결재란을 표시',
            showAsSchedule:'목록을 일정표로 표시',
            showImageTitle:'옵션중 하나를 선택하면 이미지와 함께 표시됩니다.',
            showSum:'합계표시',
            showSumTitle:'필드별로 그룹으로 묶어 목록을 표시 할때 합계가 표시 됩니다.',
            simpleMode:'간단히',
            textMode:'텍스트형',
            use:'사용',
            useAsUserList:'사용자 목록 카테고리로 사용',
            useColorTag:'칼라태그 기능 사용',
            userInfo:'사용자 정보',
            userList:'사용자 목록',
            useSimpleList:'자료 목록을 간단하게 표시',
            unavailableShared:'공유필드에서는 사용할 수 없습니다.',
            viewCategory:'시작할때 카테고리 판넬 숨기기',
            viewedListNum:'최근 본 항목 표시 개수(입력 후 Enter를 치면 저장 됩니다.)',
            viewInformation:'내용보기 판넬 보이기 고정',
            viewOrAll:'전체목록/안본목록'
        },  
        error:{
            downloadLimit:'첨부된 파일을 한번에 모두 다운로드 하려면 크롬브라우저를 사용해야 합니다. <br>첫번째 파일만 다운로드 합니다.',
            hasNoColorDataCategory:'칼라정보들을 가진 파일들이 저장된 카테고리가 아닙니다.',
            lowerLevelToCopy:'복사할 권한이 없습니다.',
            lowerLevelToDownload:'다운로드 권한이 없습니다.',
            lowerLevelToEmail:'이메일 보내기 권한이 없습니다.',
            lowerLevelToPrint:'프린트 권한이 없습니다.',
            lowerLevelToWrite:'자료의 등록이나 수정 권한이 없습니다.',
            mailError:'메일 발송에 문제가 있어 메일이 발송 되지 못했습니다.',
            needPassword:'수정을 하기 위해서는 보안을 위하여 현재의 비밀번호를 입력하셔야 합니다.',
            needCheckPassword:'새로운 비밀번호를 한번 더 입력 해 주세요',
            needNewPassword:'새로운 비밀번호를 입력 해 주세요',
            needSharp:'첫번째 글자는 반드시 "#"이어야 합니다.',
            noCategory:'존재하지 않거나 삭제 된 카테고리입니다. 잠시후 재시작합니다.',
            noColorchipCategory:'칼라코드관리 카테고리가 아닙니다.',
            noSelectedField:'선택된 필드가 없습니다.',
            noImage:'이미지를 찾을 수 없습니다.',
            noMangerMail:"관리자 이메일이 설정 돼 있지 않거나 올바르지 않아 메일을 보낼 수 없습니다.",
            noSession:'오래동안 사용되지 않아 자동으로 로그아웃 된것 같습니다. 다시 로그아웃 해 주세요',
            noSubcategory:'선택한 자료의 구성에 필요한 서브 카테고리들이 생성되지 않았거나 삭제됐을 가능성이 높습니다. \n이문제의 해결을 위해서는 관리자에게 문의 해 주세요. \nError code:101',
            notImageFile:'사용가능한 이미지 포맷이 아닙니다.',
            notUser:'존재하지 않는 사용자입니다.',
            optionError:'필드나 카테고리 설정에 문제가 발견되었습니다. 관리자에게 문의 해 주세요\nError code:109',
            overContactFields:'contact 필드설정이 1개 이상 설정 되어 프로그램을 계속 사용할 수 없습니다. 관리자에게 문의 해 주세요\nError code:109',
            removeGetRecord:'야래 항목이 설정 돼 있습니다. 동시에 사용할 수 없습니다',
            removeGetValue:'위 항목이 설정 돼 있습니다. 동시에 사용할 수 없습니다',
            removeImpossible:'클론 카테고리에서는 현재 카테고리에서 수정된 자료에 대해서만 삭제할수 있습니다. 소스카테고리에서만 지울 수 있습니다.<br>소스카테고리:',
            typeNotMatch:'선택된 필드가 타겟의 필드 형식과 같지 않아 복사하여 사용할 수 없습니다.',
            twoPasswordNotMatch:'새 비밀번호가 일치하지 않습니다. 다시 입력 해 주세요',
            unknwonColor:'잘못된 색정보입니다.',
            wrongPassword:'잘못된 비밀번호 입니다.'
        },
        login:{
            initShortcut:'바로가기 초기화',
            loginInfo:'아이디 또는 비밀번호가 올바르지 않습니다.',
            login:'로그인',
            logout:'로그아웃',
            password:'비밀번호',
            programRestart:'새로운 비밀번호로 다시 로그인 합니다.',
            userId:'아이디'
        },
        main:{
            add:'추가',
            attachFile:'첨부파일',
            basicInfo:'기본정보',
            browse:'찾아보기',
            canceled:'취소 됐습니다.',
            category:'카테고리',
            caution:'주의',
            colortag:'칼라태그',
            commentList:'대화 목록',
            compareData:'자료비교',
            complete:'완료',
            config:'설정',
            connectedCategory:' 카테고리와 연결된 카테고리 입니다',
            copied:'복사 되었습니다.',
            copyMessage:'선택한 카테고리로 자료가 복사됩니다. 진행하시겠습니까?',
            contentTitle:'내용:',
            default:'기본',
            delAlert:'삭제된 자료는 복구 될 수 없습니다. 삭제 하시겠습니까?',
            delAll:'선택된 자료 모두 삭제',
            deleteComplete:'삭제 되었습니다.',
            deleteData:'자료 삭제',
            department:'소속',
            description:'내용:',
            download:'다운로드',
            dropHere:'링크할 데이터를 두번 클릭하거나 끌어서 여기에 놓으세요.',
            duplicated:'이미 추가 된 데이터 입니다.',
            editable:'수정모드가 활성화 됐습니다. 수정할 항목을 클릭 하세요.',
            editDay:'수정일',
            email:'이메일',
            emailNotify:'선택된 자료의 정보가 자동으로 이메일로 보내집니다. 또한 추가로 전할 내용을 덧 붙일수도 있습니다.<br>받는 사람을 추가하려면 ","로 구분하여 입력 해 주세요.',
            emptyItem:'선택',
            file:'파일',
            gridTitle:'자료목록',
            historyList:'버전목록',
            item:'항목',
            lastModifyBy:'마지막 수정자',
            loadingImage:'이미지를 준비중입니다. <br>잠시만 기다려 주세요',
            mailComplete:'메일이 정상적으로 발송 되었습니다.',
            message:'메시지',
            name:'이름',
            networkProblem:'넷트웍 연결에 문제가 있습니다.',
            newComment: '새대화', 
            no:'아니오',
            noComment:'대화가 없습니다.',
            noFile:'파일이 없습니다.',
            noData:'현재 카테고리에는 데이터가 없습니다.',
            noPermission:'글을 삭제하거나 변경하기 위한 권한이 부족합니다.',
            nothingtoSend:'보낼 자료가 선택 되지 않았습니다.',
            nothingToPrint:'인쇄할 내용이 없습니다.',
            notice:'알림',
            ok:'확인',
            onlyNumber:'숫자만 입력 가능합니다.',
            permissionError:'권한없음',
            phone:'전화',
            pluginIntro:'내용을 보려면 해당 아이템을 클릭 하세요.',
            printIt:'인쇄',
            refImageTitle: '첨부',
            refresh:'새로고침',
            regDate:'입력일',
            reset:'리셋',
            saveByNewDesign:'새로운 칼라웨이와 함께 별도의 새로운 디자인으로 저장됩니다.<br>잔향하시겠습니까?',
            saveClose:'저장후 닫기',
            saveDesign:'디자인 저장',
            saving:'저장중입니다...',
            selectedItems:'선택된 자료 수',
            selectOnlyOne:'두개 이상의 자료가 선택 됐습니다. 하나만 선택 해 주세요',
            selectValue:'값 선택',
            showImage:'이미지보기',
            showOffice:'문서보기',
            submitComment:'새글 올리기',
            title:'제목',
            total:'합계',
            typeHex:'Hex code 입력',
            updateChanges:'변경된 사항을 저장 하시겠습니까?',
            updateDesign:'변경된 칼라웨이와 함께 저장되며 이전 디자인으로 되돌릴 수 없습니다.<br> 진행하시겠습니까?',
            user:'등록자',
            yes:'예'
        },
        member:{
            addr1:'주소 1',
            addr2:'주소 2',
            birthday:'생년월일',
            cellPhone:'모바일폰',
            change:'변경',
            changePassword:'비밀번호 변경',
            checkNewPassword:'새 비밀번호 확인',
            email:'이메일',
            female:'여',
            male:'남',
            name:'이름',
            nickname:'별명',
            newPassword:'새 비밀번호',
            passwordForSecurity:'보안을 위하여 비밀번호를 입력 해 주세요',
            phone:'전화번호',
            photo:'사진',
            position:'직책',
            profile:'개인정보',
            sex:'성별',
            task:'업무',
            title:'제목',
            updateComplete:'변경된 사용자 정보가 정상적으로 저장 되었습니다.',
            userId:'ID'
        },         
        menu:{
            byGroup:'그룹으로 분류',
            cc:'참조',
            changeForm:'양식변경',
            chart:'챠트',
            clear:'초기화',
            close:'닫기',
            colorChip:'칼라칩',
            colorway:'자동배색 칼라링',
            copy:'복사',
            copyToClipboard:'클립보드에 링크주소 복사',
            copyToCurrentCategory:'현재 카테고리에 복사',
            edit:'수정',
            editable:'수정모드/보호모드',
            download:'첨부파일 다운로드',
            facebook:'페이스북에 업로드',
            fromAnotherDesign:'칼라웨이 가져오기',
            getERPData:'ERP에서 칼라웨이정보 가져오기',
            history:'버전',
            isEditable:'수정모드가 활성화 됐습니다.',
            layoutType:'목록타입',
            mapping:'매핑',
            menu:'메뉴',
            newPost:'새로작성',
            newColorway:'새 칼라웨이',
            next:'다음',
            notice:'공지사항',
            print:'선택자료 인쇄',
            printInfo:'출력정보',
            recentItem:'최근사용 항목',
            recipient:'받는사람',
            remove:'삭제',
            restore:'복원',
            saveAsNew:'새로 저장',
            seeDetail:'자세히보기',
            sendEmail:'이메일 보내기',
            setting:'설정',
            slideshow:'슬라이드쇼',
            today:'오늘',
            uneditable:'보호모드가 활성화 됐습니다.',
            update:'업데이트'
        }, 
        message:{     
            agree:'승인',
            agreement:'승인요청',   
            allowEdit:'문서수정 허용',
            approval:'결재',
            approvalRequest:'결재요청',  
            approved:'이미 결재하신 문서 입니다.',
            checkAgree:'승인됨',
            checkApproval:'결재됨',
            checkConfirm:'확인함',
            checkInterval:'새 메시지 체크 간격(바로 적용하려면 F5키를 이용해 다시 시작)',
            complete:'메시지가 전송 되었습니다.',
            confirm:'확인',
            confirmation:'확인요청', 
            date:'보낸날짜',
            deleteMessages:'선택된 메시지들이 삭제 됩니다. 삭제하시겠습니까?',
            didAgree:'승인하신 문서입니다.',
            didApproval:'결재하신 문서입니다.',
            didConfirm:'확인하신 문서입니다.',
            docIndex:'문서번호',
            documentBox:'문서함',
            documentIn:'받은 문서함',
            documentOut:'보낸 문서함',
            messageBox:'메시지함',
            messageIn:'받은 메시지',
            messageType:'요청형식',
            messageOut:'보낸 메시지', 
            needAgree:'승인 표시가 필요한 문서입니다. 승인 하시려면 버튼을 클릭 해 주세요.',
            needApproval:'결재가 필요한 문서입니다. 확인 하셨으면 아래 결재란의 해당 칸을 클릭 해 주세요.',
            needConfirm:'확인 표시가 필요한 문서입니다. 확인 하셨으면 버튼을 클릭 해 주세요.',
            noMessage:'메시지가 없습니다.',
            normal:'일반',
            noPermission:'읽기 권한이 없습니다. 관리자에게 문의 해 주세요.',
            noTarget:'메시지를 받을 대상이 없습니다.',
            noUse:'사용안함',
            okAgree:'문서를 승인 했습니다.',
            okApproval:'문서를 결재 했습니다.',
            okConfirm:'문서를 확인 했습니다.', 
            opened:'읽음',
            readDate:'읽은날짜',
            readBy:'읽은사람',
            reciever:'받는사람',
            reply:'답장',
            selectReciever:'수신자 선택',
            selectType:'문서 요청 형식을 선택 해 주세요.',
            sender:'보낸사람',
            sendingDoc:'문서 전송',
            sendingMessage:'메시지 전송', 
            sentRecent:'최근 보냈던 사람들중에서 선택',
            statusAgree:'승인상태',
            statusApproval:'결재상태',
            statusConfirm:'확인상태',
            time30:'30초',
            time5m:'5분',
            time30m:'30분',
            time60m:'1시간',  
            unAvailableUser:'선택된 정보를 볼 권한이 없는 대상입니다.',
            unread:'읽지 않음',
            writeMessage:'메시지 작성'
        },
        program:{
            about:'Overview',
            contact:'문의',
            currentLicense:'GPLv3',
            currentVersion:'2.0',            
            email:'master@dipol.co.kr',
            license:'라이센스',
            programName:'프로그램 이름',            
            version:'버전'
        },  
        search:{
            byKeyword:'키워드검색',
            byOutput:'업무내용 선택',
            categoryName:'카테고리 이름',
            date:'날짜',
            detailSearch:'상세검색',
            fieldSearch:'필드검색',
            findSimilar:'가까운 색 검색',
            from:'부터',
            fromAll:'모든 카레고리에서',
            fromCurrent:'선택된 카테고리내에서',
            fromEdited:'변경된 자료 중에서',
            fromSourceCategory:'소스카테고리 기준으로',
            inWork:'업무검색',
            inWorkContent:'업무내용 검색',            
            month:' 월',
            monthly:'연도별/월별',
            nothingToSearch:'검색할 내용이 없습니다.',
            noValues:'검색을 위해 입력된 조건이 없습니다.',
            search:'검색',
            searchAll:'전체에서 검색',
            searchOption:'검색조건',
            searchResult:'검색결과',
            to:'까지',  
            year:'년도',
            yearRequired:'연도 먼저 선택해 주세요.'
        },
        upload:{
            addAttachFile:'추가된 파일:',
            addFile:'파일추가',
            addReferFile:'참고파일추가',
            addRow:'열추가',
            attachedFile:'첨부된 파일:',
            autoText:'포함된 글자 입력 후 아래 방향키 사용',
            cancel:'취소',
            cellEditTip:'입력후 Enter 키를 누르면 적용됩니다.',
            datagrpTitle:'관련자료 선택',
            delAllRow:'모든 열 제거',
            delRow:'선택된 열 제거',
            dblclickToDel:'파일첨부를 취소 하려면 해당파일을 더블클릭 하세요.',
            edit:'수정',
            edited:'업데이트 됐습니다.',
            entry:'입력',
            extractingColor:'색을 추출하고 있습니다. 잠시만 기다려 주세요...',            
            fileName:'파일명',
            fileSize:'파일크기',
            image:'이미지',
            imageTooBig:'이미지가 표시하기에 너무 커서 작게 표시합니다. 원본은 다운로드해서 보시기 바랍니다.',
            imageURL:'(이미지 URL)',
            insertFile:'파일(들)을 내용에 삽입',
            linkWindowTitle:'링크할 자료를 선택',  
            modified:'마지막 수정일',
            newEditor:'별도 창에서 편집',
            noMoreDel:'더 이상 삭제할 수 없습니다.',
            noneSelected:'선택된 아이템이 없습니다.', 
            noSelectedAction:'선택된 Action이 없습니다.',
            numOfColors:'칼라 수',
            numericOnly:'숫자로만 입력',
            option1:'첫째조건',
            option2:'둘째조건', 
            pleaseWait:'업로드 중입니다. 잠시만 기다려 주세요...',
            posted:'등록 됐습니다.',
            readOnly:'(읽기전용)',
            saved:'저장 되었습니다.',
            saveHistory:'새버전 추가',
            savedAsUpdatedList:'수정 내역이 기록 됩니다.',
            select:'선택',
            selectCategory:'카테고리 선택',
            selectData:'자료 선택',
            selectFirstOption:'첫번째 조건을 선택 해 주세요.',
            selectSecondOption:'두번째 조건 없이 첫번째 값만 입력 하시겠습니까?',
            submit:'등록',
            uploading:'업로드 중...',
            uploadTitle:'새 자료 작성',
            uploadTitleInEdit:'자료 수정'
        },    
        viewer:{
            activateChanged:'변경된 자료 표시',
            additionalInfo:'추가된 정보',
            approval:'승인',
            approveCancel:'이미 결재가 된 문서 입니다. 결재를 취소하시겠습니까?',
            approveDocu:'결재하시겠습니까?',
            byImage:'이미지 강조',
            cannotDirectModify:'직접수정이 불가능한 항목입니다.',
            cantChangeForm:'현재 카테고리에서는 사용할 수 없는 양식입니다.',
            commentDeleted:'삭제된 댓글이 있습니다.',
            copyToClipboard:'Ctrl + C를 눌러 다음을 클립보드에 복사하세요\n주소에 /T를 붙이면 가장 작은 썸네일, /M을 붙이면 큰 썸네일을 얻을 수 있습니다.' ,
            defaultView:'기본',
            detailView:'자세히보기',
            formNeedDbgrp:'이 폼을 사용하기 위해서는 데이터그룹필드가 설정 돼 있어야합니다. 관리자에게 문의해 주세요.',
            gallery:'갤러리',
            html:'Html',
            imageList:'이미지나열',
            information:'프로그램',
            invoice:'인보이스',
            newCommentAdded:'새로운 댓글이 추가 되었습니다.',
            noAttached:'첨부파일은 보내지 않음',
            noForm:'지정된 폼이 존재하지 않습니다.',
            noRecipient:'받을 사람 주소가 하나 이상 필요합니다.',
            normalView:'일반',
            noPower:'결재 권한이 없습니다.',
            noShowData:'슬라이드쇼를 하기 위한 아이템이 없습니다.',
            nothingToDisplay:'표시할 내용이 없습니다.',
            open:'열기',
            preview:'미리보기',
            problemInData:'잘못된 입력 정보가 있습니다.',
            recentlyViewed:'최근 본 항목들',
            selectItemFirst:'먼저 내용을 표시할 항목을 선택해 주세요.',
            send:'보내기',
            sendbyEmail:'이메일로 보내기',
            simpleList:'단순나열',
            showAttachImage:'첨부파일이 이미지이면 본문에 삽입',
            unavailableForm:'현재 카테고리에서는 사용할 수 없는 양식입니다. 관리자 설정이 필요합니다.',
            viewDocument:'내용보기',
            withAttached:'첨부파일 포함',
            withCompanyInfo:'아래에 로고와 회사정보 표시',
            withRegister:'등록한 사람 표시',
            withRegistDay:'등록일 표시',
            wrongForm:'카테고리의 폼 설정에 이상한 점이 발견 됐습니다. 관리자에게 문의 바랍니다.'
        },
        work:{
            activityList:'활동 목록',
            addNew:'새로만들기',
            contentOutput:'산출물',
            contentReport:'보고서',
            contentService:'고객요청',            
            createNewActivity:'새 업무 추가',
            deleteActivity:'삭제',
            deleteActivityTitle:'프로젝트 삭제',
            directInput:'직접입력',
            loading:'준비중...',
            tabNotSelected:'선택된 탭이 없습니다.',
            onlyMine:'내가 올린 자료만 보기',
            position:'직급',
            seeActContent:'활동내용',
            seeActivity:'영업활동',
            seeMore:'더 보기',
            workChance:'Overview',
            worklistTitle:'업무목록',
            updateActivity:'업데이트'
        }
    }
};

var userLanguage = navigator.language;//Chrome
if(userLanguage === undefined){
    userLanguage = navigator.userLanguage; //IE
}
userLanguage  = userLanguage.slice(0, 2);

var localLanguage;
if(userLanguage == 'ko'){
    localLanguage = 'Korean';
}
if(userLanguage == 'en'){
    localLanguage = 'English';
}

// localLanguage = 'English';
loc = languageSet[localLanguage]; //globals.js의 loc에 저장

function callLanguagePack(type, name) {
    var value = loc[type][name];
    return value;
}

function setKoreanFormat(){
    submitDateFormat = 'Y/m/d';
    if (Ext.Date) {
        Ext.Date.monthNames = ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'];

        Ext.Date.getShortMonthName = function(month) {
            return "" + (month + 1);
        };

        Ext.Date.monthNumbers = {
            "1월": 0,
            "2월": 1,
            "3월": 2,
            "4월": 3,
            "5월": 4,
            "6월": 5,
            "7월": 6,
            "8월": 7,
            "9월": 8,
            "10월": 9,
            "11월": 10,
            "12월": 11,
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3,
            "5": 4,
            "6": 5,
            "7": 6,
            "8": 7,
            "9": 8,
            "10": 9,
            "11": 10,
            "12": 11
        };

        Ext.Date.getMonthNumber = function(name) {
            return Ext.Date.monthNumbers[name.substring(0, name.length - 1)];
        };

        Ext.Date.dayNames = ["일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"];

        Ext.Date.getShortDayName = function(day) {
            return Ext.Date.dayNames[day].substring(0, 1);
        };

        Ext.Date.formatCodes.a = "(this.getHours() < 12 ? '오전' : '오후')";
    }
    Ext.define('Override.grid.header.Container', {
        override: 'Ext.grid.header.Container',
        sortAscText  : "오름차순 정렬",
        sortDescText : "내림차순 정렬",
        lockText     : "칼럼 잠금",
        unlockText   : "칼럼 잠금해제",
        columnsText  : "칼럼 목록"
    });    

    if(Ext.grid.feature.Grouping ){
        Ext.apply(Ext.grid.feature.Grouping.prototype, {
            emptyGroupText : '(None)',
            groupByText    : '현재 필드로 그룹핑합니다.',
            showGroupsText : '그룹으로 보여주기'

        });
    }  
    if(Ext.form.HtmlEditor){
        Ext.apply(Ext.form.HtmlEditor.prototype, {
            createLinkText : 'URL을 입력해주세요:',
            buttonTips : {
                bold : {
                    title: '굵게 (Ctrl+B)',
                    text: '선택한 텍스트를 굵게 표시합니다.',
                    cls: 'x-html-editor-tip'
                },
                italic : {
                    title: '기울임꼴 (Ctrl+I)',
                    text: '선택한 텍스트를 기울임꼴로 표시합니다.',
                    cls: 'x-html-editor-tip'
                },
                underline : {
                    title: '밑줄 (Ctrl+U)',
                    text: '선택한 텍스트에 밑줄을 표시합니다.',
                    cls: 'x-html-editor-tip'
                },
                increasefontsize : {
                    title: '글꼴크기 늘림',
                    text: '글꼴 크기를 크게 합니다.',
                    cls: 'x-html-editor-tip'
                },
                decreasefontsize : {
                    title: '글꼴크기 줄임',
                    text: '글꼴 크기를 작게 합니다.',
                    cls: 'x-html-editor-tip'
                },
                backcolor : {
                    title: '텍스트 강조 색',
                    text: '선택한 텍스트의 배경색을 변경합니다.',
                    cls: 'x-html-editor-tip'
                },
                forecolor : {
                    title: '글꼴색',
                    text: '선택한 텍스트의 색을 변경합니다.',
                    cls: 'x-html-editor-tip'
                },
                justifyleft : {
                    title: '텍스트 왼쪽 맞춤',
                    text: '왼쪽에 텍스트를 맞춥니다.',
                    cls: 'x-html-editor-tip'
                },
                justifycenter : {
                    title: '가운데 맞춤',
                    text: '가운데에 텍스트를 맞춥니다.',
                    cls: 'x-html-editor-tip'
                },
                justifyright : {
                    title: '텍스트 오른쪽 맞춤',
                    text: '오른쪽에 텍스트를 맞춥니다.',
                    cls: 'x-html-editor-tip'
                },
                insertunorderedlist : {
                    title: '글머리 기호',
                    text: '글머리 기호 목록을 시작합니다.',
                    cls: 'x-html-editor-tip'
                },
                insertorderedlist : {
                    title: '번호 매기기',
                    text: '번호 매기기 목록을 시작합니다.',
                    cls: 'x-html-editor-tip'
                },
                createlink : {
                    title: '하이퍼링크',
                    text: '선택한 텍스트에 하이퍼링크를 만듭니다.',
                    cls: 'x-html-editor-tip'
                },
                sourceedit : {
                    title: '소스편집',
                    text: '소스편집 모드로 변환합니다.',
                    cls: 'x-html-editor-tip'
                }
            }
        });
    }
    if(Ext.PagingToolbar){
        Ext.apply(Ext.PagingToolbar.prototype, {
            beforePageText : "페이지",
            afterPageText  : "/ {0}",
            firstText      : "첫 페이지",
            prevText       : "이전 페이지",
            nextText       : "다음 페이지",
            lastText       : "마지막 페이지",
            refreshText    : "새로고침",
            displayMsg     : "전체 {2} 중 {0} - {1}",
            emptyMsg       : '표시할 데이터가 없습니다.'
        });
    }    
}
